set_cover_position_and_tilt:
  name: Set cover position and tilt
  description: Set blind position and tilt
  target:
    entity:
      integration: overkiz
      domain: cover
  fields:
    position:
      name: Position
      description: Position of the cover
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    tilt_position:
      name: Tilt Position
      description: Tilt position of the cover
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
